set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set number              " show line numbers

syntax on
"colorscheme distinguished
"colorscheme atom-dark

colorscheme ariake-dark
set background=dark

" using Source Code Pro
set anti enc=utf-8
set guifont=Source\ Code\ Pro\ 11
