set expandtab          " tabs are spaces
set tabstop=4          " number of visual spaces per TAB
set softtabstop=4      " number of spaces in tab when editing
set shiftwidth=4
set number             " show line numbers
set showmatch          " highlight matching [{()}]
set colorcolumn=81
set smartindent        " Do smart autoindenting when starting a new line

" set colours
syntax on
"colorscheme distinguished
"colorscheme atom-dark
colorscheme ariake-dark
set background=dark

" use Source Code Pro
set anti enc=utf-8
set guifont=Source\ Code\ Pro\ 11


" Searching
set incsearch           " search as characters are entered
set hlsearch            " highlight matches
