if [ -f ~/.bashrc ]
then
    source ~/.bashrc
fi


# silence zsh message
export BASH_SILENCE_DEPRECATION_WARNING=1

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/mdekauwe/Downloads/google-cloud-sdk/path.bash.inc' ]; then . '/Users/mdekauwe/Downloads/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/mdekauwe/Downloads/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/mdekauwe/Downloads/google-cloud-sdk/completion.bash.inc'; fi
