if [ -f ~/.bashrc ]
then
    source ~/.bashrc
fi

# added by gwgen_conda installer
alias gwgen="/Users/mdekauwe/gwgen-conda/bin/gwgen"

# added by gwgen-conda installer
export PATH="/Users/mdekauwe/gwgen-conda/bin:$PATH"

# silence zsh message
export BASH_SILENCE_DEPRECATION_WARNING=1
